### ISSUE TITLE
Can it be used on gtavc

### ISSUE THREAD

**Issue by axb996** [SanketBhat/GTASACheatKeyboard#1]
How can I use it on VC? Thank you

**Comment by SanketBhat** [comment]
Hi, To use it on gtavc you will have to replace gtasa cheat codes to gtavc cheat codes in GTASACheatService.kt..

To be clear from my side, it is an Android app which I created because on Android other keyboards did not open on top of the game, so this app creates a notification and on clicking on it it opens a keyboard with static cheat codes.

**Comment by axb996** [comment]
Yes, I made it, thank you very much for your example, have a nice life:)
